apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socialserver
  template:
    metadata:
      labels:
        app: socialserver
    spec:
      containers:
        - name: socialserver
          image: mike-virtual-machine1:5000/socialserver:v1.4
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: socialserver
spec:
  selector:
    app: socialserver
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP