apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialserver
  template:
    metadata:
      labels:
        app: socialserver
    spec:
      containers:
        - name: socialserver
          image: mike-virtual-machine1:5000/socialserver:v1.2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: socialserver
spec:
  selector:
    app: socialserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer