apiVersion: v1
kind: Namespace
metadata:
  name: external-apps
  labels:
    istio-injection: disabled
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mongo1
  namespace: external-apps
subsets:
  - addresses:
      - ip: 10.0.0.8
    ports:
      - port: 27017
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mongo2
  namespace: external-apps
subsets:
  - addresses:
      - ip: 10.0.0.9
    ports:
      - port: 27017
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mongo3
  namespace: external-apps
subsets:
  - addresses:
      - ip: 10.0.0.10
    ports:
      - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  # 此处 metadata.name 的值要和 endpoints 中的 metadata.name 的值保持一致
  name: mongo1
  namespace: external-apps
spec:
  ports:
    - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  # 此处 metadata.name 的值要和 endpoints 中的 metadata.name 的值保持一致
  name: mongo2
  namespace: external-apps
spec:
  ports:
    - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  # 此处 metadata.name 的值要和 endpoints 中的 metadata.name 的值保持一致
  name: mongo3
  namespace: external-apps
spec:
  ports:
    - port: 27017


