apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: rs0-mongo0
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: mongodb
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: LoadBalancer
