apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: kong
spec:
  ports:
    - name: http
      port: 1337
      targetPort: 1337
  selector:
    application: konga
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konga-ingress
  namespace: kong
spec:
  ingressClassName: nginx
  rules:
    - host: konga
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: konga
                port:
                  number: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:0.14.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
          env:
            - name: KONGA_BACKEND_URL
              value: "http://kong-admin:8444"
#            - name: NO_AUTH
#              value: "false"
#            - name: DB_ADAPTER
#              value: "mysql"
#            - name: DB_URI
#              value: "mysql://admin:admin@172.80.1.100/konga"
      nodeName: mike-virtual-machine1